### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by dsme94** [pieqq/PyGeoIpMap#19]
> ➜  PyGeoIpMap git:(master) ✗ sudo pip3 install -r requirements.txt
> Collecting https://github.com/matplotlib/basemap/archive/v1.0.7rel.tar.gz (from -r requirements.txt (line 3))
>   Downloading https://github.com/matplotlib/basemap/archive/v1.0.7rel.tar.gz
>      | 164.3MB 16.0MB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-gni68bkb/setup.py", line 1, in <module>
>         import sys, glob, os, numpy, subprocess
>     ImportError: No module named 'numpy'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-gni68bkb/

I think this will be sorted by moving numpy to one of the first packages to be installed.

**Comment by ghost** [comment]
sudo pip3 install numpy
